### ISSUE TITLE
Critical : Paper updated the mysql connector for security reasons : java.lang.ClassNotFoundException: com.mysql.jdbc.jdbc2.optional.MysqlDataSource

### ISSUE THREAD

**Issue by Over2Craft-mc** [pavog/craftconomy3#106]
Paper updated the mysql connector for security reasons https://papermc.io/downloads #588
We cannot use latest paper version anymore since it will throw java.lang.ClassNotFoundException: com.mysql.jdbc.jdbc2.optional.MysqlDataSource

**Comment by Over2Craft-mc** [comment]
duplicate of #105 (title not very explicite)

**Comment by pavog** [comment]
Hi, I have released a new Craftconomy version 3.5.4 which should fix the problem with newer Paper versions.

**Comment by Over2Craft-mc** [comment]
Thanks for your work :D
