### ISSUE TITLE
Bug with message in the chat for /money give

### ISSUE THREAD

**Issue by aurel85** [pavog/craftconomy3#111]
Hi,

When a player receives a /give or /money give there is no message that appears in the chat while with /money pay it's ok.
Before, I was using the last version of Craftconomy by gretman and there was no such problem.
Could you do something about it because it's confusing for players not to see the rewards they receive (in the console everything is there and their balance is well updated).

Screenshots :
03.05 01:06:55 [Server] INFO aurel85 issued server command: /money pay Kotaras 1
03.05 01:07:00 [Server] INFO aurel85 issued server command: /money give Kotaras 1

![Capture](https://user-images.githubusercontent.com/24486147/116834241-70870e80-abbd-11eb-9beb-a3e6e9253e88.PNG)

![Capture2](https://user-images.githubusercontent.com/24486147/116834244-7381ff00-abbd-11eb-9f69-3ed2b36a72ff.PNG)

I am using the latest version of the plugin (3.3.4) and Paper 1.16.5.

Thank you in advance.

**Comment by pavog** [comment]
Thanks, I will look into it soon.
