### ISSUE TITLE
/craftconomy reload = Internal Error

### ISSUE THREAD

**Issue by Blackyvk** [pavog/craftconomy3#25]
After trying to reload the plugin "/craftconomy reload" you get this

![imagen](https://user-images.githubusercontent.com/9063912/50719732-4073e300-1077-11e9-94b5-bac698d17b7e.png)

Errror
https://pastebin.com/raw/5uyuwCBd

And leaves the plugin completely unusable until a server restart.

**Comment by pavog** [comment]
Hey, I released a new version [here](https://github.com/pavog/craftconomy3/releases/tag/3.5.0).
Can you test it please?

**Comment by Blackyvk** [comment]
nice, it seems to be working good at the moment, thanks!
