### ISSUE TITLE
Vault is not detecting v3.5.0

### ISSUE THREAD

**Issue by doddsy** [pavog/craftconomy3#26]
Noticed Vault was not detecting version 3.5.0. Not sure if I've done something wrong though, it's been a while since I've looked at Minecraft plugins.

Vault version `v1.7.1-b91` (latest on their spigot page)
CC3 version `3.5.0-SNAPSHOT`
`/vault-info` shows
```
[Vault] Vault v1.7.1-b91 Information
[Vault] Economy: Essentials Economy [Essentials Economy]
[Vault] Permission: LuckPerms [LuckPerms, SuperPerms]
[Vault] Chat: LuckPerms [LuckPerms]
```

I might be wrong, but I think it's because CC3 finishes loading after vault. Console indicates that CC3 only finishes loading after Vault, leading Vault to detect Essentials Economy instead.

Hope you're able to fix this, or if not point me in the right direction instead 😄 
Thanks!

**Comment by itsdoddsy** [comment]
Hey there, any progress on this? I'd quite like to use Craftconomy over other economy related plugins.

Thanks!

**Comment by pavog** [comment]
Hey, thank you for reporting this issue and sorry for the delay.

I tried loading Craftconomy before Vault in the plugin.yml, see [this commit](https://github.com/pavog/craftconomy3/commit/4cbcd83bd98fb17c99590d8e0085877edb3451bc).
It did not fix the problem...

I think I need to hook into Vault's economy system to enable the Vault support, not sure how this could have ever worked since there has never been such a hook.

I'll ping you on any updates.

**Comment by pavog** [comment]
Today I finally had the time to look into this and I found the problem:
Craftconomy does not have a proper Vault API implementation.
Before I add one I have a question (probably to some one of you who is a developer of a plugin that uses Vault to interact with Craftconomy):
If you create a bank account via Vault, should the player it is created for be automatically charged for the money the creation of a bank account costs? Or do you want to charge the player by your own?

**Comment by pavog** [comment]
Hey there, I pushed a new release. You can pick it up [here](https://github.com/pavog/craftconomy3/releases/tag/3.5.1).
Please test the Vault integration and give me some feedback.

**Comment by doddsy** [comment]
Hi there, I've been testing this for around 5 days now and this release seems to be working perfectly. Thanks so much!
