### ISSUE TITLE
Incompatibility with Vault.

### ISSUE THREAD

**Issue by Weark** [pavog/craftconomy3#40]
Since I updated craftcononey3 for your project, it stopped working with several savings pluvins that I use.
Examples:
1- Pay to repair items in Essentials plugin signs.
2- The PlayerShops GUI [BSP], which I use to make shop.

The strange thing is that they were not for everyone, some continue to function as the:
1- https://www.spigotmc.org/resources/auction-house-the-ultimate-auction-plugin-1-8-8-1-13-2.60325/
2- https://www.spigotmc.org/resources/shopgui-1-7-1-13.6515/
...

Could you fix, or compile a Vault with full compatibility with the craftcononey3 plugin?

**Comment by pavog** [comment]
Does any plugin show an error message / exception with stack trace?

I'm working on the correct implmentation of vault at the moment and keep you updated.

**Comment by Weark** [comment]
1- In my Full PvP server which has EssentialsX, when trying to repair the sign it does not return error but says that I do not have enough money being that I have, I do not think it has identified the economy of CraftConomy3 and is trying to use the of EssentialsX.
Note: In my EssentialsX with [depend = CraftConomy3]
On the same server I have an X1 plugin that worked with the Vault economy, I was using the old CraftConomy3, now that I updated to the new one it can not use the economy of CraftConomy3 and it gets used to EssentialsX.

2- I tested on my local server without EssentialsX to see if the "PlayerShops GUI [BSP]" plugin worked, but unfortunately when I tried to create a shop I said "I had not identified an economy system".

I upgraded to Vault for version 1.7.2 and it did not work.
https://www.spigotmc.org/resources/vault.34315/

I very much hope it solves this problem as soon as possible, I will be waiting for it, as soon as I update, release the Download so that I can test.

Thank you very much for the support.

**Comment by Weark** [comment]
Hello pavog,

Any news?

I'm waiting for an update so I can download and test.

Thank you.

**Comment by pavog** [comment]
Hi Weark, 

yes, you can test a new version if you want.
Can I send you an E-Mail to the address you linked on your Youtube channel?

**Comment by Weark** [comment]
> Hi Weark,
> 
> yes, you can test a new version if you want.
> Can I send you an E-Mail to the address you linked on your Youtube channel?

Yes, this is my email address: douglasgameerr@gmail.com
It will take that you have solved the problem with Vault this will help my server a lot.
I'll be waiting for the email, thank you.

**Comment by Androkai** [comment]
I also experienced a problem with [BossShopPro](https://github.com/Blackixx/BossShopPro) always telling me "You don't have an economy account!" but it works nicely for [AreaShop](https://github.com/NLthijs48/AreaShop/). I took a look into the code of booth. Booth do a null check for `.getEconomy()` but BossShopPro additionally checks for `.getEconomy().hasAccount(player.getName())` which seems to return false.

**Comment by pavog** [comment]
@Weark @Androkai Hello there, I just uploaded a new release of craftconomy3 which should fix your problems. Please test the newest version (3.5.2) and report any issues.

**Comment by Androkai** [comment]
Works for all of my plugins without any problems now. Can be closed from my side. 👍

**Comment by pavog** [comment]
This should work in 3.5.2. Please open another issue if the error still occurs.
