### ISSUE TITLE
money create command returns "null"

### ISSUE THREAD

**Issue by DJShocker** [pavog/craftconomy3#43]
Attempting to use /money create returns null.

MineCraft 1.13.2

**Comment by pavog** [comment]
Thank you for the issue report.
I already found the problem and fixed it for the next release: There was a typo in the message identifier for the "account already exists" message.

I will release the new version in a few days and ping you to test it :)

**Comment by pavog** [comment]
Hi @DJShocker I released a new version of Craftconomy3 (v 3.5.2) and the issue should be fixed now.
Please download the newest release from [here ](https://github.com/pavog/craftconomy3/releases) and test it again. 

Thank you :)

**Comment by pavog** [comment]
Closing this. If the problem still occurs please open another issue.
