### ISSUE TITLE
SQL Error?

### ISSUE THREAD

**Issue by Xuwznln** [pavog/craftconomy3#83]
Got this when starting using this version of craftconomy3. Any solution to solve? Thanks!

`Survival-1: [22:11:35 WARN]: java.sql.SQLException: Subquery returns more than 1 row
Survival-1: [22:11:35 WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
Survival-1: [22:11:35 WARN]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3933)
Survival-1: [22:11:35 WARN]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3869)
Survival-1: [22:11:35 WARN]: 	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2524)
Survival-1: [22:11:35 WARN]: 	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2675)
Survival-1: [22:11:35 WARN]: 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2465)
Survival-1: [22:11:35 WARN]: 	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1912)
Survival-1: [22:11:35 WARN]: 	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:2020)
Survival-1: [22:11:35 WARN]: 	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
Survival-1: [22:11:35 WARN]: 	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
Survival-1: [22:11:35 WARN]: 	at com.greatmancode.craftconomy3.storage.sql.SQLStorageEngine.getBalance(SQLStorageEngine.java:368)
Survival-1: [22:11:35 WARN]: 	at com.greatmancode.craftconomy3.account.Account.getBalance(Account.java:147)
Survival-1: [22:11:35 WARN]: 	at net.milkbowl.vault.economy.plugins.Economy_Craftconomy3.getBalance(Economy_Craftconomy3.java:279)
Survival-1: [22:11:35 WARN]: 	at net.milkbowl.vault.economy.plugins.Economy_Craftconomy3.getBalance(Economy_Craftconomy3.java:121)
Survival-1: [22:11:35 WARN]: 	at net.milkbowl.vault.economy.AbstractEconomy.getBalance(AbstractEconomy.java:20)`

**Comment by Xuwznln** [comment]
Got it fixed by removing duplicated entries. Thanks.

**Comment by pavog** [comment]
Glad you got that sorted out on your own. I may need to add some more checks to the db to avoid errors like these.
Thanks for reporting.
